import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fraunces = localFont({
  src: "../public/assets/fonts/fraunces/Fraunces-VariableFont_SOFT,WONK,opsz,wght.ttf",
  variable: "--font-fraunces-family",
  display: "swap",
});

const manrope = localFont({
  src: "../public/assets/fonts/manrope/Manrope-VariableFont_wght.ttf",
  variable: "--font-manrope-family",
  display: "swap",
});

const frauncesStatic = localFont({
  src: "../public/assets/fonts/fraunces/static/Fraunces_144pt-SemiBold.ttf",
  variable: "--font-fraunces-semibold-family",
  weight: "600",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${manrope.variable} ${frauncesStatic.variable} h-full antialiased`}
    >
      <body className="min-h-full">{children}</body>
    </html>
  );
}
